name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/yanis42/hackeroot-build-test:main
    runs-on: ubuntu-22.04
    stategy:
      matrix:
        DEBUG_NO_F3DEX3: RELEASE=0 CPP_DEFINES=-DENABLE_F3DEX3=0
        DEBUG_F3DEX3: RELEASE=0 CPP_DEFINES=-DENABLE_F3DEX3=1
        RELEASE_NO_F3DEX3: RELEASE=1 CPP_DEFINES=-DENABLE_F3DEX3=0
        RELEASE_F3DEX3: RELEASE=1 CPP_DEFINES=-DENABLE_F3DEX3=1
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /baseroms .

    # Install the required pip packages
    - name: Setup Python
      run: |
        python3 -m pip install --user colorama ansiwrap attrs watchdog python-Levenshtein "mapfile-parser>=1.2.1,<2.0.0" "rabbitizer>=1.0.0,<2.0.0"
        python3 -m pip install --upgrade attrs pycparser
    
    # Setup the project
    - name: Setup
      run: make setup -j$(nproc)

    # Build the project
    - name: Build (Debug, No F3DEX3)
      run: ${{ matrix.DEBUG_NO_F3DEX3 }} make -j$(nproc)

    # Build the project
    - name: Build (Debug, F3DEX3)
      run: make clean && ${{ matrix.DEBUG_F3DEX3 }} make -j$(nproc)

    # Build the project
    - name: Build (Release, No F3DEX3)
      run: make clean && ${{ matrix.RELEASE_NO_F3DEX3 }} make -j$(nproc)

    # Build the project
    - name: Build (Release, F3DEX3)
      run: make clean && ${{ matrix.RELEASE_F3DEX3 }} make -j$(nproc)
