name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/yanis42/hackeroot-build-test:main
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /baseroms .

    # Install the required pip packages
    - name: Setup Python
      run: |
        python3 -m pip install --user colorama ansiwrap attrs watchdog python-Levenshtein "mapfile-parser>=1.2.1,<2.0.0" "rabbitizer>=1.0.0,<2.0.0"
        python3 -m pip install --upgrade attrs pycparser
    
    # Build the project
    - name: Build
      run: |
        make setup -j$(nproc)
        make -j$(nproc)
