name: Format check

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  setup:
    name: Setup Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  check-main:
    name: Check all files
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.action }} == 'push'
    steps:
    - name: Check file's formatting
      run: ./tools/check_format.py

  check-pr:
    name: Check modified files
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.action }} == 'pull_request'
    steps:
    - name: Check file's formatting
      run: ./tools/check_format.py --verbose --compare-to origin/develop/2.1.0
